// HumorLibrary — the actual joke content HumorEngine draws from. Pure
// data, no logic: every entry is a short, personality-first line, never a
// restatement of numbers ("le spese sono passate da 50 € a 200 €" is
// exactly what this library refuses to say — see humorEngine.js/
// jokeEvaluator.js for how that's enforced). Spendy teases the SITUATION
// ("hai offerto la cena anche al cuoco?"), never the person, never with a
// number attached.
//
// Structure, per language:
//   categories.<categoryId>.high / .low   — a category's own voice, used
//     for "this category is unusually high/low" insights (spike,
//     recurring, trend, single-transaction — see humorEngine.js's
//     directionFor). Hero categories (ristoranti/spesa/shopping/
//     trasporti/casa) get the richest banks since the brief's own
//     examples are all in these.
//   types.<BEHAVIOR_TYPE>                 — situational, not tied to any
//     one category's imagery (budget, savings, streaks, unusual
//     purchase/frequency).
//   types.obiettivi                       — reserved for a future
//     goal-linked insight type; nothing in BehaviorEngine emits it yet
//     (that would mean touching BehaviorEngine, out of scope this round),
//     kept here purely so the library is ready when it does.
//   types.fallback                        — last-resort net for any
//     category+type combo not covered above; still personality-first,
//     never a data description.
//
// Adding a language: add one more top-level key with the same shape —
// nothing in humorEngine.js or jokeEvaluator.js needs to change.
export const humorLibrary = {
  it: {
    categories: {
      ristoranti: {
        high: [
          'Hai offerto la cena anche al cuoco? 😂',
          'Il tuo ristorante di fiducia ti ha quasi messo una statua all’ingresso.',
          'A questo punto ti conviene aprire un conto con il cameriere.',
          'Hai mangiato per due... o forse per quattro.',
          'Il menu degustazione questa volta lo hai fatto tutto tu, da solo.',
          'Occhio, tra un po’ ti chiedono la mancia sull’affitto.',
          'Stai sponsorizzando personalmente la ristorazione locale.',
          'Il tavolo con il tuo nome sopra è ormai ufficiale.',
          'Chef’s kiss al tuo portafoglio, che ha retto comunque.',
          'Hai fatto il pieno di pizza più che di benzina, sembra.',
          'Tra antipasti e dolci, il conto ha fatto la sua gara personale.',
          'Il cameriere inizia a salutarti per nome. Non è un buon segno (per il portafoglio).',
        ],
        low: [
          'Questo mese hai pagato così poco al ristorante che quasi non ti riconosco. 😂',
          'Il tuo ristorante di fiducia si starà chiedendo dove sei finito.',
          'Hai scoperto il segreto della cucina di casa, a quanto pare.',
          'Il forno di casa ha lavorato più del delivery, stavolta.',
          'Il cameriere ti aspetta ancora, tipo tumbleweed nel deserto.',
          'Sei passato in modalità chef casalingo senza preavviso.',
          'Il tuo grembiule sta vivendo il suo momento di gloria.',
          'Hai lasciato i ristoranti in pausa questo mese. Rispetto.',
          'Persino la pizza d’asporto si sente un po’ trascurata.',
          'Complimenti, hai battuto la tentazione del delivery.',
          'Il tuo frigo ha fatto più straordinari del solito, eh?',
          'Ti sei quasi laureato in economia domestica questo mese.',
        ],
      },
      spesa: {
        high: [
          'La dispensa è pronta per un piccolo assedio. 😂',
          'Hai fatto scorta come se arrivasse l’inverno nucleare.',
          'Il carrello questa volta aveva bisogno di rinforzi.',
          'Il supermercato ti ha quasi dedicato una corsia.',
          'A questo punto potresti aprire un minimarket in salotto.',
          'Hai comprato abbastanza da nutrire anche i vicini.',
          'La cassiera ormai ti conosce di vista, immagino.',
          'Il tuo frigo ha bisogno di un’estensione.',
          'Sembra che tu abbia fatto la spesa per tre mesi, non uno.',
          'Il portafoglio ha sentito ogni singolo scaffale, stavolta.',
          'Hai riempito il carrello come fosse un rifugio antiatomico.',
          'Bentornata, abbondanza.',
        ],
        low: [
          'Questo mese hai tenuto il portafoglio al guinzaglio. 😏',
          'La dispensa si è organizzata da sola, a quanto pare.',
          'Hai fatto la spesa in modalità minimalista, e si vede.',
          'Il carrello questa volta era quasi timido.',
          'Bravo, hai resistito alla tentazione degli scaffali.',
          'Il frigo è leggero, ma la coscienza è pulita.',
          'Sei entrato ed uscito dal supermercato quasi in silenzio.',
          'Hai fatto shopping alimentare col freno a mano tirato, e ha funzionato.',
          'Poca spesa, tanta disciplina.',
          'Il tuo carrello ha fatto dieta insieme a te, sembra.',
          'Hai lasciato quasi tutto sugli scaffali, complimenti.',
          'Questo mese la lista della spesa era davvero corta.',
        ],
      },
      shopping: {
        high: [
          'L’armadio aveva ancora spazio?! 😂',
          'Il tuo armadio questo mese ha bisogno di più spazio.',
          'Hai fatto shopping come se i saldi finissero domani.',
          'Le etichette con il prezzo si sono un po’ spaventate.',
          'Il corriere ormai ha il tuo citofono tra i preferiti.',
          'Hai aggiornato il guardaroba, il conto in banca un po’ meno.',
          'A questo punto ti serve un secondo armadio, non uno sconto.',
          'Il tuo stile è cresciuto, il saldo un po’ meno.',
          'Hai shoppato come se fosse una gara a squadre.',
          'Le buste della spesa... no aspetta, quelle sono shopping bag.',
          'Il tuo portafoglio ha fatto la sua personale sfilata di moda.',
          'Bentornato nel tuo nuovo guardaroba, praticamente.',
        ],
        low: [
          'Il tuo armadio oggi può finalmente respirare.',
          'Hai resistito ai saldi come un vero eroe.',
          'Zero acquisti d’impulso questo mese, che disciplina.',
          'Il corriere si è quasi dimenticato di te, in senso buono.',
          'Hai lasciato le vetrine solo a guardare, stavolta.',
          'L’armadio non ha ricevuto nuovi inquilini questo mese.',
          'Hai fatto shopping solo con gli occhi, e va benissimo così.',
          'Il tuo guardaroba resta invariato, e il conto ti ringrazia.',
          'Niente nuovi acquisti, tanta autodisciplina.',
          'Hai detto no ai saldi, e i saldi se la sono presa un po’ male.',
          'Il tuo stile stavolta è rimasto sullo storico, e va bene così.',
          'Complimenti, hai vinto tu contro le vetrine.',
        ],
      },
      trasporti: {
        high: [
          'La macchina beve più di te. 😂',
          'Il distributore ormai ti riconosce dal rumore del motore.',
          'Hai fatto il giro d’Italia, o solo quello dell’isolato?',
          'La tua auto merita un nome proprio, a questo punto.',
          'Il pieno questa volta ha fatto le ore piccole col tuo portafoglio.',
          'Sembra che tu stia sponsorizzando personalmente la benzina.',
          'La tua macchina ha un appetito niente male questo mese.',
          'Il tachimetro dei consumi ha lavorato più di te.',
          'Hai fatto più chilometri del previsto, o solo più soste al distributore?',
          'Il serbatoio ha vissuto una vita intensa questo mese.',
          'Tra pedaggi e benzina, il viaggio è costato più della meta.',
          'La tua auto si sente coccolata, il conto un po’ meno.',
        ],
        low: [
          'Con quello che hai risparmiato, la macchina ti ha quasi pagato lei. 😂',
          'Hai scoperto le gioie della bicicletta, sembra.',
          'Il distributore si starà chiedendo dove sei finito.',
          'La tua auto è rimasta a riposo più del solito.',
          'Hai risparmiato benzina come un vero maestro zen.',
          'Il tachimetro dei consumi ha preso una pausa questo mese.',
          'Sei diventato un maestro del risparmio su ruote.',
          'Meno strada, meno spese: bella equazione.',
          'Il serbatoio è rimasto quasi pieno tutto il mese, complimenti.',
          'Hai lasciato l’auto in garage più spesso, e si vede.',
          'I mezzi pubblici ti hanno adottato questo mese, pare.',
          'Il tuo portafoglio ha fatto il pieno di sollievo, non di benzina.',
        ],
      },
      casa: {
        high: [
          'Accidenti a queste bollette!',
          'La bolletta questo mese è arrivata senza bussare.',
          'Qualcosa in casa ha lavorato più del solito, eh?',
          'Le bollette hanno deciso di fare gli straordinari.',
          'La lavatrice merita una medaglia, il conto no.',
          'Casa tua consuma più energia di una centrale, a quanto pare.',
          'Il contatore gira che è un piacere, per lui.',
          'Le bollette ti hanno mandato un saluto un po’ salato.',
          'Sembra che tu abbia riscaldato anche il quartiere.',
          'Il conto della luce si è preso una rivincita questo mese.',
          'Casa tua sta vivendo il suo periodo più energico.',
          'Le utenze hanno deciso di farsi notare, stavolta.',
        ],
        low: [
          'La bolletta stavolta si è presentata con educazione.',
          'Le bollette questo mese sono state quasi timide.',
          'Casa tua ha fatto economia senza dirtelo.',
          'Il contatore ha preso una pausa, sembra.',
          'Le utenze si sono comportate benissimo questo mese.',
          'Bel risparmio silenzioso su luce e gas.',
          'La bolletta ha deciso di essere gentile, per una volta.',
          'Casa tua è entrata in modalità risparmio energetico.',
          'Le spese di casa sono scese senza fare rumore.',
          'Il contatore ti ringrazia per la pausa.',
          'Bollette leggere, coscienza pulita.',
          'Casa tua ha risparmiato energia più di quanto pensassi.',
        ],
      },
      abbonamenti: {
        high: [
          'Quanti servizi in streaming stai davvero guardando?',
          'La lista degli abbonamenti si allunga più della tua serie preferita.',
          'Hai collezionato abbonamenti come fossero francobolli.',
          'Ogni mese nasce un nuovo abbonamento, sembra.',
          'Il tuo calendario di rinnovi è più pieno del tuo tempo libero.',
          'Stai pagando per intrattenimento che forse nemmeno apri.',
          'Gli abbonamenti si sono messi in fila e sono aumentati.',
          'A questo punto meriti un abbonamento anche per gli abbonamenti.',
        ],
        low: [
          'Hai fatto pulizia tra gli abbonamenti, e si vede.',
          'Qualche servizio in meno questo mese, bella sfoltita.',
          'Gli abbonamenti hanno perso qualche iscritto: tu.',
          'Hai detto basta a un paio di rinnovi automatici, bravo.',
          'La lista dei servizi attivi si è alleggerita.',
          'Meno abbonamenti, più spazio nel budget.',
          'Hai fatto ordine tra le sottoscrizioni, complimenti.',
          'Qualche rinnovo cancellato, il conto ti ringrazia.',
        ],
      },
      tecnologia: {
        high: [
          'Un nuovo gadget è appena entrato in famiglia.',
          'Il negozio di elettronica ti aspettava a braccia aperte.',
          'Hai fatto un upgrade... anche al tuo conto in negativo.',
          'La tecnologia ti ha conquistato di nuovo questo mese.',
          'Un altro dispositivo si è unito alla collezione.',
          'Il tuo angolo tech si è appena arricchito.',
          'Hai ceduto al fascino del nuovo modello, eh?',
          'La cassa dell’elettronica ha stampato uno scontrino niente male.',
        ],
        low: [
          'Nessun nuovo gadget questo mese: autocontrollo da manuale.',
          'Hai resistito al fascino delle novità tech, complimenti.',
          'Il negozio di elettronica non ti ha visto passare.',
          'Zero acquisti tecnologici, tanta forza di volontà.',
          'Hai lasciato le novità sullo scaffale, stavolta.',
          'Il tuo angolo tech resta invariato, e va benissimo.',
          'Hai detto no all’ultimo modello, che disciplina.',
          'Niente nuovi dispositivi: il portafoglio ti applaude.',
        ],
      },
      salute: {
        high: [
          'Ti stai proprio prendendo cura di te questo mese.',
          'La farmacia ti ha visto più spesso del solito.',
          'Investire su di te non ha prezzo... anche se il conto un po’ se ne accorge.',
          'Il tuo benessere questo mese ha avuto la priorità, giustamente.',
          'Hai speso per la tua salute più del solito, e va benissimo.',
          'La farmacia sotto casa ti considera quasi di famiglia.',
          'Prendersi cura di sé costa, ma vale sempre la pena.',
          'Questo mese hai messo il tuo benessere al primo posto.',
        ],
        low: [
          'Poche spese in salute questo mese, tutto tranquillo.',
          'La farmacia questo mese ti ha visto poco, meglio così.',
          'Nessun acciacco, nessuna spesa: che mese fortunato.',
          'Sei stato alla larga dalla farmacia, in senso buono.',
          'Salute in ordine, conto in ordine.',
          'Un mese tranquillo anche per il tuo benessere fisico.',
          'Poche spese di salute, spero solo perché stai bene.',
          'Il tuo corpo ti ha lasciato in pace questo mese, a livello di conto.',
        ],
      },
      svago: {
        high: [
          'Qualcuno si sta godendo la vita questo mese.',
          'Il tuo svago ha avuto un mese niente male.',
          'Hai investito parecchio nel divertimento, e si vede.',
          'Il tempo libero questo mese ti è costato, ma che vita.',
          'Hai fatto il pieno di svago più che di altro.',
          'Il divertimento questo mese non si è tirato indietro.',
          'Hai speso per goderti la vita, e onestamente approvo.',
          'Il tuo lato più giocoso ha vinto questo round.',
        ],
        low: [
          'Poco svago questo mese: tutto lavoro e niente gioco?',
          'Il divertimento ha preso una pausa questo mese.',
          'Hai messo il tempo libero un po’ in secondo piano.',
          'Il tuo lato più giocoso si è fatto piccolo piccolo.',
          'Poche spese di svago, spero non per mancanza di voglia.',
          'Il divertimento aspetta il suo turno, a quanto pare.',
          'Questo mese il relax è passato in sordina.',
          'Poco svago, tanta serietà. Anche troppo, forse?',
        ],
      },
      viaggi: {
        high: [
          'Le valigie hanno lavorato più di te questo mese.',
          'Sembra che tu abbia inseguito l’estate in giro per il mondo.',
          'Il passaporto sta ancora fumando dai timbri.',
          'Hai investito parecchio in nuovi orizzonti, letteralmente.',
          'Le compagnie aeree ti ringraziano personalmente.',
          'Hai collezionato più viaggi che souvenir, sembra.',
          'Il conto è rimasto a casa a badare alle valigie.',
          'Questo mese l’avventura ha vinto sul portafoglio.',
        ],
        low: [
          'Le valigie sono rimaste tranquille in un angolo questo mese.',
          'Nessuna nuova avventura, ma il conto ti ringrazia.',
          'Il passaporto si riposa un po’ questo mese.',
          'Hai scelto la comodità di casa, stavolta.',
          'Niente voli, niente valigie: mese di riposo.',
          'I viaggi aspettano il momento giusto, sembra.',
          'Hai messo in pausa l’esploratore che c’è in te.',
          'Zero trasferte questo mese, tanta stabilità.',
        ],
      },
      altro: {
        high: [
          'Questa categoria ha avuto il suo momento di gloria questo mese.',
          'Qualcosa di inaspettato ha bussato al tuo portafoglio.',
          'Le spese varie si sono fatte notare, eh?',
          'Un mese pieno di piccole sorprese di spesa.',
          'Le voci minori questa volta hanno pesato come quelle grandi.',
          'Anche l’imprevisto ha voluto la sua parte questo mese.',
          'Qualche spesa fuori programma ha trovato spazio nel budget.',
          'Le eccezioni questo mese sono state più numerose del previsto.',
        ],
        low: [
          'Nessuna sorpresa di spesa questo mese, che pace.',
          'Le voci minori sono rimaste davvero minori, stavolta.',
          'Un mese senza troppi imprevisti sul portafoglio.',
          'Le spese varie si sono tenute basse basse.',
          'Poche eccezioni, tanta prevedibilità: non male.',
          'Il budget non ha avuto sorprese fuori programma.',
          'Questo mese l’imprevisto ha deciso di non presentarsi.',
          'Le spese fuori categoria sono rimaste in silenzio.',
        ],
      },
    },
    types: {
      budget_exceeded: [
        'Il budget ha alzato bandiera bianca questo mese.',
        'Abbiamo sfondato il tetto del budget, ma niente panico.',
        'Il portafoglio ha chiesto una pausa, capita.',
        'Il budget si è preso una libertà questo mese.',
        'Siamo andati oltre, ma insieme rimettiamo le cose in ordine.',
        'Il budget ha detto basta un po’ prima del previsto.',
        'Abbiamo sforato, ma è solo un mese, non una condanna.',
        'Il conto ha superato il limite, respiriamo e ripartiamo.',
      ],
      // Not over budget yet, but close — spendyCoach.js's tiers 5/6 draw
      // from these instead of one fixed sentence whenever no single
      // category is the obvious cause (see behaviorEngine.js's
      // checkBudget for the two thresholds these correspond to).
      budget_high: [
        'Il budget ha il fiatone: siamo praticamente al traguardo e il mese non è finito.',
        'Ok, livello rosso: il portafoglio chiede una tregua.',
        'Siamo praticamente a secco, e il mese ha ancora strada da fare.',
        'Il conto sta guardando il calendario con un certo nervosismo.',
        'Il budget ha tirato il freno a mano da solo, giusto per farsi notare.',
        'Poco margine rimasto, meglio procedere con i piedi di piombo.',
      ],
      budget_rising: [
        'Il budget ha ingranato una marcia in più, e non in senso buono.',
        'Stiamo correndo un po’ troppo per essere solo a metà mese.',
        'Il conto ha iniziato a sudare, giusto un pochino.',
        'Il portafoglio si guarda intorno con aria preoccupata.',
        'Passo veloce questo mese, meglio non affondare ancora l’accelerator.',
        'Il budget si è messo a correre: teniamolo d’occhio insieme.',
      ],
      budget_respected: [
        'Guarda un po’... qualcuno sta imparando! 😂',
        'Budget rispettato: dammi il cinque.',
        'Hai tenuto il timone dritto tutto il mese.',
        'Il portafoglio questo mese ti ringrazia personalmente.',
        'Missione budget: completata con successo.',
        'Hai giocato in defense e hai vinto la partita.',
        'Il conto è sereno, e anche io con lui.',
        'Bel colpo: budget rispettato senza drammi.',
      ],
      savings_vs_usual: [
        'Il tuo conto oggi può dormire tranquillo.',
        'Hai speso meno del solito, e si sente.',
        'Il portafoglio si è preso una vacanza dallo stress.',
        'Risparmio inaspettato: chi sei e cosa hai fatto al vero te?',
        'Il conto ha ritrovato un po’ di respiro questo mese.',
        'Hai messo il turbo al risparmio, sembra.',
        'Il tuo solito mese ha avuto un plot twist positivo.',
        'Meno uscite del previsto: bella sorpresa.',
      ],
      positive_streak: [
        'Sei sotto budget da un po’, e comincia a diventare un’abitudine.',
        'Questa costanza comincia a piacermi parecchio.',
        'Un’altra striscia positiva: stai diventando bravo in questo.',
        'Il tuo budget ha trovato un ritmo niente male.',
        'Mese dopo mese, questa disciplina si vede.',
        'Continua così e mi tocca aggiornare la tua reputazione.',
      ],
      negative_streak: [
        'Il budget è sotto pressione da un po’, diamogli un’occhiata insieme.',
        'Qualche mese difficile di fila, ma si può sempre correggere la rotta.',
        'Il conto chiede una mano, senza drammi.',
        'È il momento di dare una piccola sistemata alle cose.',
        'Un po’ di attenzione in più non farebbe male, dai.',
        'Rimettiamo insieme le cose in ordine, con calma.',
      ],
      unusual_purchase: [
        'Una new entry nelle tue spese questo mese!',
        'Ecco una categoria che non si vedeva da un po’.',
        'Una spesa mai vista prima: benvenuta alla festa.',
        'Il tuo portafoglio ha scoperto un nuovo territorio.',
        'Una new entry di tutto rispetto tra le tue spese.',
        'Novità in arrivo tra le tue abitudini di spesa.',
      ],
      unusual_frequency_high: [
        'Quante volte sei tornato lì questo mese? Ho perso il conto.',
        'Ci sei tornato così tante volte che ormai sembra un abbonamento.',
        'Questa categoria ti ha visto più spesso del solito.',
        'Sembra diventata la tua meta preferita del mese.',
        'Ci sei praticamente di casa, a questo punto.',
        'Frequenza record questo mese, complimenti alla costanza.',
      ],
      unusual_frequency_low: [
        'Sei stato in modalità silenziosa su questa categoria.',
        'Poche visite questo mese, quasi in pausa.',
        'Questa categoria si è presa una vacanza da te.',
        'Ci sei passato solo di sfuggita questo mese.',
        'Quasi assente, in questa categoria. Rispetto.',
        'Hai tenuto le distanze, e si vede.',
      ],
      obiettivi: [
        'Il tuo obiettivo si sta avvicinando, un passo alla volta.',
        'Ogni piccolo risparmio ti porta più vicino al traguardo.',
        'Il salvadanaio degli obiettivi sta crescendo bene.',
        'Continua così, l’obiettivo è più vicino di quanto pensi.',
        'Il tuo obiettivo ti sta facendo l’occhiolino.',
        'Sei al {percentage} di "{goal}". Mancano {remaining}: non mollare adesso.',
        '"{goal}" e’ al {percentage}. Il difficile lo hai gia’ fatto.',
        'Ancora {remaining} e "{goal}" smette di essere un’idea.',
        '{amount} messi da parte per "{goal}". Non e’ fortuna, sei tu.',
      ],
      small_expenses_add_up: [
        'Sembrano innocue, poi si mettono d’accordo tra loro.',
        'Una volta non pesa. {count} volte iniziano a fare squadra.',
        '{count} piccole spese, {amount} in totale. La matematica non fa sconti.',
        'Nessuna di loro e’ colpevole. Tutte insieme, un po’ si’.',
        'Le briciole, se sono {count}, diventano una fetta.',
        'Spendere poco {count} volte non e’ spendere poco.',
        'Il portafoglio non si e’ accorto di niente. Io si’.',
        '{amount} andati via a piccoli sorsi, senza un brindisi.',
      ],
      fallback: [
        'Ho notato qualcosa di interessante nelle tue spese questo mese.',
        'C’è un piccolo movimento da segnalare, niente di grave.',
        'Ho tenuto d’occhio questa situazione, e mi ha fatto sorridere.',
        'Piccola stranezza rilevata, ma nulla di preoccupante.',
        'Ho notato qualcosa fuori dal solito, giusto per informarti con stile.',
        'Una piccola curiosità dal tuo portafoglio questo mese.',
      ],
    },
  },

  en: {
    categories: {
      ristoranti: {
        high: [
          'Did you buy the chef a car this month? 😂',
          'Your favorite restaurant is putting up a statue of you.',
          'At this point you might as well open a tab with the waiter.',
          'You ate like you were feeding a small crowd.',
          'You ran the whole tasting menu solo this time.',
          'Careful, next they’ll ask for a tip on your rent.',
          'You’re personally sponsoring the local restaurant scene.',
          'There’s basically a table with your name on it now.',
          'Chef’s kiss to your wallet, which somehow survived.',
          'Looks like you filled up on pizza more than gas.',
          'Between starters and dessert, the bill had its own little race.',
          'The waiter’s starting to greet you by name. Not a great sign (for your wallet).',
        ],
        low: [
          'You barely spent anything at restaurants this month, who even are you. 😂',
          'Your favorite spot is probably wondering where you went.',
          'Looks like you rediscovered your own kitchen.',
          'Your oven pulled more shifts than delivery did, this time.',
          'The waiter’s still waiting, tumbleweed-style.',
          'You went full home-chef mode without warning.',
          'Your apron is having its moment of glory.',
          'You gave restaurants a break this month. Respect.',
          'Even the takeout pizza feels a little neglected.',
          'Nicely done, you outran the delivery temptation.',
          'Your fridge has been working serious overtime, huh?',
          'You basically earned a minor in home economics this month.',
        ],
      },
      spesa: {
        high: [
          'The pantry is stocked for a small siege. 😂',
          'You shopped like winter was never ending.',
          'The cart needed backup this time.',
          'The supermarket practically named an aisle after you.',
          'At this point you could open a mini-market in your living room.',
          'You bought enough to feed the neighbors too.',
          'The cashier probably knows your face by now.',
          'Your fridge needs an extension.',
          'Feels like you shopped for three months, not one.',
          'Your wallet felt every single shelf this time.',
          'You filled that cart like it was a bunker.',
          'Welcome back, abundance.',
        ],
        low: [
          'You kept your wallet on a short leash this month. 😏',
          'The pantry basically organized itself, apparently.',
          'You went full minimalist at the store, and it shows.',
          'The cart was almost shy this time.',
          'Nicely done resisting the shelves.',
          'Fridge is light, conscience is clean.',
          'You were in and out of the store in near silence.',
          'You did grocery shopping with the brakes on, and it worked.',
          'Small cart, big discipline.',
          'Your cart went on a diet right along with you.',
          'You left most of it on the shelves, well done.',
          'That grocery list was seriously short this month.',
        ],
      },
      shopping: {
        high: [
          'Did the closet still have room?! 😂',
          'Your closet needs more space this month.',
          'You shopped like the sale ends tomorrow.',
          'The price tags got a little nervous.',
          'The delivery guy has your buzzer saved as a favorite.',
          'Wardrobe: upgraded. Bank balance: not so much.',
          'At this point you need a second closet, not a discount.',
          'Your style leveled up, your balance leveled down.',
          'You shopped like it was a competitive sport.',
          'Those aren’t grocery bags... those are shopping bags.',
          'Your wallet just walked its own personal runway.',
          'Welcome to your new wardrobe, basically.',
        ],
        low: [
          'Your closet can finally breathe today.',
          'You resisted the sale like a true hero.',
          'Zero impulse buys this month, what discipline.',
          'The delivery guy almost forgot about you, in a good way.',
          'You left the shop windows just for looking this time.',
          'The closet got no new residents this month.',
          'You went window shopping only, and that’s perfectly fine.',
          'Your wardrobe stays the same, and your balance thanks you.',
          'No new purchases, so much self-control.',
          'You said no to the sale, and the sale took it a little personally.',
          'Your style stayed classic this round, and that works too.',
          'Congrats, you beat the shop windows this time.',
        ],
      },
      trasporti: {
        high: [
          'The car drinks more than you do. 😂',
          'The gas station knows your engine sound by now.',
          'Did you drive across the whole country, or just the block?',
          'Your car deserves an actual name at this point.',
          'Filling the tank kept your wallet up late this time.',
          'Feels like you’re personally sponsoring gas prices.',
          'Your car had quite the appetite this month.',
          'The fuel gauge worked harder than you did.',
          'More miles than planned, or just more stops at the pump?',
          'The tank lived a full life this month.',
          'Between tolls and fuel, the trip cost more than the destination.',
          'Your car feels pampered, your balance a little less so.',
        ],
        low: [
          'With what you saved, the car basically paid for itself. 😂',
          'Looks like you discovered the joys of biking.',
          'The gas station is probably wondering where you went.',
          'Your car got more rest than usual.',
          'You saved fuel like a true zen master.',
          'The consumption gauge took a break this month.',
          'You’ve become a savings master on wheels.',
          'Less driving, less spending: nice little equation.',
          'The tank stayed nearly full all month, well done.',
          'You left the car in the garage more often, and it shows.',
          'Public transport basically adopted you this month.',
          'Your wallet filled up on relief, not gas.',
        ],
      },
      casa: {
        high: [
          'These utility bills, honestly.',
          'The bill showed up unannounced this month.',
          'Something at home worked overtime, huh?',
          'The bills decided to put in extra hours.',
          'The washing machine deserves a medal, your balance doesn’t.',
          'Your place is apparently drawing power like a small plant.',
          'The meter is having the time of its life.',
          'The bills sent you a rather pricey little hello.',
          'Feels like you heated the whole neighborhood too.',
          'The electric bill got its revenge this month.',
          'Your home is going through its most energetic phase.',
          'Utilities decided to make themselves known this time.',
        ],
        low: [
          'The bill showed up politely this time.',
          'The bills were almost shy this month.',
          'Your home saved money without even telling you.',
          'The meter took a little break, it seems.',
          'Utilities behaved really well this month.',
          'Nice quiet savings on power and gas.',
          'The bill decided to be kind, for once.',
          'Your home went into energy-saving mode.',
          'Home expenses dropped without making a sound.',
          'The meter thanks you for the break.',
          'Light bills, clean conscience.',
          'Your home saved more energy than you’d think.',
        ],
      },
      abbonamenti: {
        high: [
          'How many streaming services are you actually watching?',
          'Your subscription list is growing faster than your favorite show.',
          'You collected subscriptions like stamps.',
          'A new subscription seems to be born every month.',
          'Your renewal calendar is fuller than your free time.',
          'You’re paying for entertainment you might not even open.',
          'Subscriptions lined up and multiplied, apparently.',
          'At this point you deserve a subscription for your subscriptions.',
        ],
        low: [
          'You did some cleanup on the subscriptions, nice.',
          'A few less services this month, good trim.',
          'Subscriptions lost a subscriber: you.',
          'You canceled a couple of auto-renewals, well done.',
          'The active services list got lighter.',
          'Fewer subscriptions, more room in the budget.',
          'You tidied up your subscriptions, nicely done.',
          'A few renewals canceled, your balance says thanks.',
        ],
      },
      tecnologia: {
        high: [
          'A new gadget just joined the family.',
          'The electronics store had its arms wide open for you.',
          'You got an upgrade... your balance got a downgrade.',
          'Tech won you over again this month.',
          'Another device just joined the collection.',
          'Your tech corner just got a little richer.',
          'You gave in to the new model’s charm, huh?',
          'The electronics till printed quite the receipt.',
        ],
        low: [
          'No new gadgets this month: textbook self-control.',
          'You resisted the tech temptation, well done.',
          'The electronics store didn’t even see you walk by.',
          'Zero tech purchases, so much willpower.',
          'You left the new stuff on the shelf this time.',
          'Your tech corner stays the same, and that’s great.',
          'You said no to the latest model, what discipline.',
          'No new devices: your wallet is applauding.',
        ],
      },
      salute: {
        high: [
          'You really took care of yourself this month.',
          'The pharmacy saw you more than usual.',
          'Investing in yourself is priceless... though your balance noticed a bit.',
          'Your wellbeing got the priority this month, rightly so.',
          'You spent more on your health than usual, and that’s just fine.',
          'The local pharmacy considers you basically family now.',
          'Taking care of yourself costs something, but it’s always worth it.',
          'You put your wellbeing first this month.',
        ],
        low: [
          'Barely any health expenses this month, all calm.',
          'The pharmacy barely saw you this month, even better.',
          'No aches, no expenses: a lucky month.',
          'You stayed clear of the pharmacy, in a good way.',
          'Health in order, balance in order.',
          'A quiet month for your physical wellbeing too.',
          'Few health expenses, hopefully just because you’re doing great.',
          'Your body left you alone this month, balance-wise.',
        ],
      },
      svago: {
        high: [
          'Somebody’s really living it up this month.',
          'Your fun budget had quite the month.',
          'You invested heavily in having a good time, and it shows.',
          'Free time cost you this month, but what a life.',
          'You filled up on fun more than anything else.',
          'Entertainment didn’t hold back this month.',
          'You spent to enjoy life, and honestly, I approve.',
          'Your playful side won this round.',
        ],
        low: [
          'Not much fun spending this month: all work, no play?',
          'Entertainment took a break this month.',
          'You put free time a little on the back burner.',
          'Your playful side went extra quiet.',
          'Little fun spending, hopefully not for lack of wanting to.',
          'Fun is apparently waiting its turn.',
          'Relaxation stayed pretty low-key this month.',
          'Little fun, lots of seriousness. Maybe too much?',
        ],
      },
      viaggi: {
        high: [
          'The suitcases worked harder than you this month.',
          'Looks like you chased summer all around the world.',
          'Your passport is still smoking from the stamps.',
          'You invested heavily in new horizons, literally.',
          'The airlines personally thank you.',
          'You collected more trips than souvenirs, it seems.',
          'The balance stayed home minding the suitcases.',
          'Adventure won over the wallet this month.',
        ],
        low: [
          'The suitcases stayed quietly in a corner this month.',
          'No new adventures, but your balance thanks you.',
          'The passport gets a little rest this month.',
          'You picked home comfort this time.',
          'No flights, no suitcases: a month of rest.',
          'Trips are apparently waiting for the right moment.',
          'You put your inner explorer on pause.',
          'Zero trips this month, so much stability.',
        ],
      },
      altro: {
        high: [
          'This category had its moment of glory this month.',
          'Something unexpected knocked on your wallet.',
          'Miscellaneous expenses made themselves known, huh?',
          'A month full of little spending surprises.',
          'The small stuff weighed in like the big stuff this time.',
          'Even the unexpected wanted its share this month.',
          'A few off-plan expenses found room in the budget.',
          'Exceptions were more numerous than expected this month.',
        ],
        low: [
          'No spending surprises this month, what peace.',
          'The small stuff stayed genuinely small this time.',
          'A month with no big surprises on the wallet.',
          'Miscellaneous expenses stayed nice and low.',
          'Few exceptions, lots of predictability: not bad.',
          'The budget had no off-plan surprises.',
          'The unexpected decided to skip this month.',
          'Out-of-category expenses stayed quiet.',
        ],
      },
    },
    types: {
      budget_exceeded: [
        'The budget just waved a white flag this month.',
        'We blew past the budget ceiling, but no panic.',
        'The wallet asked for a break, it happens.',
        'The budget took a little liberty this month.',
        'We went over, but together we’ll sort it out.',
        'The budget called it quits a bit early.',
        'We overspent, but it’s one month, not a life sentence.',
        'The balance went past the limit, let’s breathe and restart.',
      ],
      budget_respected: [
        'Well look at that... someone’s learning! 😂',
        'Budget respected: high five.',
        'You kept the wheel steady all month.',
        'The wallet personally thanks you this month.',
        'Budget mission: accomplished.',
        'You played defense and won the game.',
        'The balance is calm, and so am I.',
        'Nice move: budget respected, no drama.',
      ],
      savings_vs_usual: [
        'Your balance can sleep peacefully today.',
        'You spent less than usual, and it shows.',
        'The wallet took a little vacation from stress.',
        'Unexpected savings: who are you and what did you do with the real you?',
        'The balance caught its breath a bit this month.',
        'You put the savings into turbo mode, apparently.',
        'Your usual month had a nice little plot twist.',
        'Fewer expenses than expected: nice surprise.',
      ],
      positive_streak: [
        'You’ve been under budget for a while now, becoming a habit.',
        'This consistency is starting to grow on me.',
        'Another good streak: you’re getting really good at this.',
        'Your budget found quite the rhythm.',
        'Month after month, this discipline shows.',
        'Keep this up and I’ll have to update your reputation.',
      ],
      negative_streak: [
        'The budget’s been under pressure for a bit, let’s take a look together.',
        'A few tough months in a row, but the course can always be corrected.',
        'The balance is asking for a hand, no drama.',
        'Time for a little tidy-up.',
        'A bit more attention wouldn’t hurt, come on.',
        'Let’s put things back in order, calmly.',
      ],
      unusual_purchase: [
        'A new entry in your expenses this month!',
        'Here’s a category that hasn’t shown up in a while.',
        'An expense never seen before: welcome to the party.',
        'Your wallet discovered new territory.',
        'A pretty notable new entry among your expenses.',
        'Something new is joining your spending habits.',
      ],
      unusual_frequency_high: [
        'How many times did you go back there this month? Lost count.',
        'You went back so many times it’s basically a membership now.',
        'This category saw you more often than usual.',
        'Seems to have become your favorite spot this month.',
        'You’re practically a regular there at this point.',
        'Record frequency this month, hats off to the consistency.',
      ],
      unusual_frequency_low: [
        'You’ve been in stealth mode on this category.',
        'Few visits this month, almost on pause.',
        'This category took a vacation from you.',
        'You barely passed through this one this month.',
        'Nearly absent on this category. Respect.',
      ],
      obiettivi: [
        'Your goal is getting closer, one step at a time.',
        'Every little saving gets you closer to the finish line.',
        'The goals jar is growing nicely.',
        'Keep it up, the goal is closer than you think.',
        'Your goal is winking at you.',
        'You’re at {percentage} of "{goal}". {remaining} to go — don’t stop now.',
        '"{goal}" is at {percentage}. The hard part is already behind you.',
        'Another {remaining} and "{goal}" stops being just an idea.',
        '{amount} set aside for "{goal}". That’s not luck, that’s you.',
      ],
      small_expenses_add_up: [
        'They look harmless, then they start teaming up.',
        'One doesn’t hurt. {count} of them start forming a committee.',
        '{count} small spends, {amount} altogether. Maths doesn’t do discounts.',
        'None of them is guilty. All of them together, a little bit.',
        'Crumbs, {count} of them, quietly become a slice.',
        'Spending little {count} times isn’t spending little.',
        'Your wallet never noticed. I did.',
        '{amount} gone in tiny sips, and not one toast.',
      ],
      budget_high: [
        'The budget is out of breath: we’re basically at the finish line and the month isn’t.',
        'We’re in the part of the month where the budget holds its breath.',
        'The budget is still standing, but it’s leaning on the wall.',
        'There’s more month left than budget, and both of us know it.',
        'The budget has entered its dramatic final act.',
        'From here on, every purchase is a plot twist.',
      ],
      budget_rising: [
        'The budget just shifted up a gear, and not the good kind.',
        'We’ve passed three quarters and the road is still long.',
        'The budget is starting to sweat a little.',
        'Still fine. Slightly less fine than yesterday.',
        'We’re at the point of the month where I start paying attention.',
        'Nothing dramatic yet. Just me, taking notes.',
      ],
      fallback: [
        'I noticed something interesting in your spending this month.',
        'There’s a small movement worth flagging, nothing serious.',
        'I kept an eye on this one, and it made me smile.',
        'Small oddity spotted, but nothing to worry about.',
        'I noticed something out of the ordinary, just letting you know with style.',
        'A little curiosity from your wallet this month.',
      ],
    },
  },

  fr: {
    categories: {
      ristoranti: {
        high: [
          'Tu as offert le dîner au chef aussi ? 😂',
          'Ton restaurant préféré t’a presque dédié une statue.',
          'À ce stade, autant ouvrir un compte avec le serveur.',
          'Tu as mangé pour deux... ou pour quatre.',
          'Le menu dégustation, tu l’as fait tout seul cette fois.',
          'Attention, bientôt on va te demander un pourboire sur le loyer.',
          'Tu sponsorises personnellement la restauration locale.',
          'La table à ton nom, c’est presque officiel maintenant.',
          'Chapeau à ton portefeuille, qui a quand même tenu bon.',
          'On dirait que tu as fait le plein de pizza plus que d’essence.',
          'Entre entrées et desserts, l’addition a fait sa propre course.',
          'Le serveur commence à te connaître par ton prénom. Mauvais signe (pour le portefeuille).',
        ],
        low: [
          'Ce mois-ci tu as si peu dépensé au restaurant que je te reconnais à peine. 😂',
          'Ton restaurant préféré doit se demander où tu es passé.',
          'On dirait que tu as redécouvert ta propre cuisine.',
          'Le four a fait plus d’heures sup que le livreur, cette fois.',
          'Le serveur attend encore, façon tumbleweed dans le désert.',
          'Tu es passé en mode chef à domicile sans prévenir.',
          'Ton tablier vit son moment de gloire.',
          'Tu as mis les restos en pause ce mois-ci. Respect.',
          'Même la pizza à emporter se sent un peu délaissée.',
          'Bravo, tu as résisté à la tentation de la livraison.',
          'Ton frigo a fait pas mal d’heures sup, non ?',
          'Tu as presque décroché un diplôme d’économie domestique ce mois-ci.',
        ],
      },
      spesa: {
        high: [
          'Le placard est prêt pour un petit siège. 😂',
          'Tu as fait des réserves comme si l’hiver nucléaire arrivait.',
          'Le chariot avait besoin de renforts cette fois.',
          'Le supermarché t’a presque dédié un rayon.',
          'À ce stade, tu pourrais ouvrir une petite épicerie dans ton salon.',
          'Tu as acheté assez pour nourrir les voisins aussi.',
          'La caissière te reconnaît sûrement de vue maintenant.',
          'Ton frigo a besoin d’une extension.',
          'On dirait que tu as fait les courses pour trois mois, pas un.',
          'Le portefeuille a senti chaque rayon, cette fois.',
          'Tu as rempli le chariot comme un abri anti-atomique.',
          'Bienvenue de retour, abondance.',
        ],
        low: [
          'Ce mois-ci tu as tenu ton portefeuille en laisse courte. 😏',
          'Le placard s’est organisé tout seul, apparemment.',
          'Tu as fait les courses en mode minimaliste, et ça se voit.',
          'Le chariot était presque timide cette fois.',
          'Bravo, tu as résisté aux rayons.',
          'Le frigo est léger, mais la conscience est tranquille.',
          'Tu es entré et sorti du supermarché presque en silence.',
          'Tu as fait les courses avec le frein à main serré, et ça a marché.',
          'Peu de courses, beaucoup de discipline.',
          'Ton chariot a fait régime avec toi, apparemment.',
          'Tu as laissé presque tout sur les rayons, bravo.',
          'La liste de courses était vraiment courte ce mois-ci.',
        ],
      },
      shopping: {
        high: [
          'L’armoire avait encore de la place ?! 😂',
          'Ton armoire a besoin de plus de place ce mois-ci.',
          'Tu as fait du shopping comme si les soldes finissaient demain.',
          'Les étiquettes de prix ont un peu paniqué.',
          'Le livreur a ton interphone en favori maintenant.',
          'Ta garde-robe s’est mise à jour, ton compte un peu moins.',
          'À ce stade il te faut une deuxième armoire, pas une remise.',
          'Ton style a grandi, ton solde un peu moins.',
          'Tu as fait du shopping comme un sport de compétition.',
          'Ce ne sont pas des sacs de courses... ce sont des sacs shopping.',
          'Ton portefeuille a fait son propre défilé de mode.',
          'Bienvenue dans ta nouvelle garde-robe, en gros.',
        ],
        low: [
          'Ton armoire peut enfin respirer aujourd’hui.',
          'Tu as résisté aux soldes comme un vrai héros.',
          'Zéro achat impulsif ce mois-ci, quelle discipline.',
          'Le livreur t’a presque oublié, dans le bon sens.',
          'Tu as laissé les vitrines juste pour regarder cette fois.',
          'L’armoire n’a reçu aucun nouveau locataire ce mois-ci.',
          'Tu as fait du lèche-vitrine seulement, et c’est très bien.',
          'Ta garde-robe reste identique, et ton compte te remercie.',
          'Aucun nouvel achat, tellement d’autodiscipline.',
          'Tu as dit non aux soldes, et les soldes l’ont pris personnellement.',
          'Ton style est resté classique ce round, et ça marche aussi.',
          'Bravo, tu as gagné contre les vitrines cette fois.',
        ],
      },
      trasporti: {
        high: [
          'La voiture boit plus que toi. 😂',
          'La station-service reconnaît déjà le bruit de ton moteur.',
          'Tu as fait le tour de la France, ou juste du quartier ?',
          'Ta voiture mérite un vrai prénom, à ce stade.',
          'Le plein t’a coûté cher en émotions cette fois.',
          'On dirait que tu sponsorises personnellement l’essence.',
          'Ta voiture a un appétit sérieux ce mois-ci.',
          'Le compteur de conso a travaillé plus que toi.',
          'Plus de kilomètres que prévu, ou juste plus d’arrêts à la pompe ?',
          'Le réservoir a vécu une vie bien remplie ce mois-ci.',
          'Entre péages et essence, le trajet a coûté plus que la destination.',
          'Ta voiture se sent chouchoutée, ton compte un peu moins.',
        ],
        low: [
          'Avec ce que tu as économisé, la voiture s’est presque payée elle-même. 😂',
          'On dirait que tu as découvert les joies du vélo.',
          'La station-service doit se demander où tu es passé.',
          'Ta voiture s’est reposée plus que d’habitude.',
          'Tu as économisé l’essence comme un vrai maître zen.',
          'Le compteur de conso a fait une pause ce mois-ci.',
          'Tu es devenu un maître de l’économie sur roues.',
          'Moins de route, moins de dépenses : belle équation.',
          'Le réservoir est resté presque plein tout le mois, bravo.',
          'Tu as laissé la voiture au garage plus souvent, et ça se voit.',
          'Les transports en commun t’ont adopté ce mois-ci, semble-t-il.',
          'Ton portefeuille a fait le plein de soulagement, pas d’essence.',
        ],
      },
      casa: {
        high: [
          'Ces factures, sérieusement.',
          'La facture est arrivée sans prévenir ce mois-ci.',
          'Quelque chose à la maison a fait des heures sup, non ?',
          'Les factures ont décidé de faire des heures supplémentaires.',
          'La machine à laver mérite une médaille, ton compte non.',
          'Ta maison consomme comme une petite centrale, apparemment.',
          'Le compteur tourne, et il adore ça.',
          'Les factures t’ont envoyé un petit bonjour salé.',
          'On dirait que tu as chauffé tout le quartier aussi.',
          'La facture d’électricité a pris sa revanche ce mois-ci.',
          'Ta maison vit sa période la plus énergique.',
          'Les charges ont décidé de se faire remarquer cette fois.',
        ],
        low: [
          'La facture s’est présentée poliment cette fois.',
          'Les factures ont été plutôt discrètes ce mois-ci.',
          'Ta maison a fait des économies sans même te le dire.',
          'Le compteur a fait une petite pause, semble-t-il.',
          'Les charges se sont très bien comportées ce mois-ci.',
          'Belle économie silencieuse sur l’électricité et le gaz.',
          'La facture a décidé d’être sympa, pour une fois.',
          'Ta maison est passée en mode économie d’énergie.',
          'Les dépenses du foyer ont baissé sans faire de bruit.',
          'Le compteur te remercie pour la pause.',
          'Factures légères, conscience tranquille.',
          'Ta maison a économisé plus d’énergie que tu ne le penses.',
        ],
      },
      abbonamenti: {
        high: [
          'Combien de services de streaming regardes-tu vraiment ?',
          'Ta liste d’abonnements grandit plus vite que ta série préférée.',
          'Tu as collectionné les abonnements comme des timbres.',
          'Un nouvel abonnement naît chaque mois, semble-t-il.',
          'Ton calendrier de renouvellements est plus rempli que ton temps libre.',
          'Tu payes pour du divertissement que tu n’ouvres peut-être même pas.',
          'Les abonnements se sont mis en file et ont augmenté.',
          'À ce stade tu mérites un abonnement pour tes abonnements.',
        ],
        low: [
          'Tu as fait le tri dans les abonnements, et ça se voit.',
          'Quelques services de moins ce mois-ci, du bon tri.',
          'Les abonnements ont perdu un abonné : toi.',
          'Tu as dit stop à quelques renouvellements automatiques, bravo.',
          'La liste des services actifs s’est allégée.',
          'Moins d’abonnements, plus de place dans le budget.',
          'Tu as fait de l’ordre dans tes abonnements, bravo.',
          'Quelques renouvellements annulés, ton compte te remercie.',
        ],
      },
      tecnologia: {
        high: [
          'Un nouveau gadget vient de rejoindre la famille.',
          'Le magasin d’électronique t’attendait à bras ouverts.',
          'Tu as fait une mise à niveau... ton compte aussi, mais en négatif.',
          'La technologie t’a encore séduit ce mois-ci.',
          'Un autre appareil a rejoint la collection.',
          'Ton coin tech vient de s’enrichir.',
          'Tu as craqué pour le nouveau modèle, hein ?',
          'La caisse du magasin d’électronique a imprimé un joli ticket.',
        ],
        low: [
          'Aucun nouveau gadget ce mois-ci : autocontrôle exemplaire.',
          'Tu as résisté au charme des nouveautés tech, bravo.',
          'Le magasin d’électronique ne t’a même pas vu passer.',
          'Zéro achat technologique, beaucoup de volonté.',
          'Tu as laissé les nouveautés sur l’étagère cette fois.',
          'Ton coin tech reste inchangé, et c’est parfait.',
          'Tu as dit non au dernier modèle, quelle discipline.',
          'Aucun nouvel appareil : ton portefeuille applaudit.',
        ],
      },
      salute: {
        high: [
          'Tu prends vraiment soin de toi ce mois-ci.',
          'La pharmacie t’a vu plus souvent que d’habitude.',
          'Investir sur toi-même n’a pas de prix... même si ton compte l’a un peu remarqué.',
          'Ton bien-être a eu la priorité ce mois-ci, à juste titre.',
          'Tu as dépensé plus que d’habitude pour ta santé, et c’est très bien.',
          'La pharmacie du coin te considère presque comme de la famille.',
          'Prendre soin de soi a un coût, mais ça vaut toujours le coup.',
          'Ce mois-ci tu as mis ton bien-être en premier.',
        ],
        low: [
          'Peu de dépenses santé ce mois-ci, tout va bien.',
          'La pharmacie t’a peu vu ce mois-ci, tant mieux.',
          'Aucun bobo, aucune dépense : quel mois de chance.',
          'Tu es resté loin de la pharmacie, dans le bon sens.',
          'Santé en ordre, compte en ordre.',
          'Un mois tranquille pour ton bien-être physique aussi.',
          'Peu de dépenses santé, j’espère juste parce que tu vas bien.',
          'Ton corps t’a laissé tranquille ce mois-ci, côté compte.',
        ],
      },
      svago: {
        high: [
          'Quelqu’un profite bien de la vie ce mois-ci.',
          'Ton budget loisirs a eu un mois du feu de dieu.',
          'Tu as pas mal investi dans le plaisir, et ça se voit.',
          'Le temps libre t’a coûté ce mois-ci, mais quelle vie.',
          'Tu as fait le plein de loisirs plus que d’autre chose.',
          'Le divertissement ne s’est pas retenu ce mois-ci.',
          'Tu as dépensé pour profiter de la vie, et honnêtement j’approuve.',
          'Ton côté joueur a gagné ce round.',
        ],
        low: [
          'Peu de loisirs ce mois-ci : que du travail, pas de jeu ?',
          'Le divertissement a fait une pause ce mois-ci.',
          'Tu as mis le temps libre un peu de côté.',
          'Ton côté joueur s’est fait tout petit.',
          'Peu de dépenses loisirs, j’espère pas par manque d’envie.',
          'Le divertissement attend son tour, apparemment.',
          'La détente est passée discrètement ce mois-ci.',
          'Peu de loisirs, beaucoup de sérieux. Peut-être même trop ?',
        ],
      },
      viaggi: {
        high: [
          'Les valises ont travaillé plus que toi ce mois-ci.',
          'On dirait que tu as chassé l’été partout dans le monde.',
          'Ton passeport fume encore à cause des tampons.',
          'Tu as pas mal investi dans de nouveaux horizons, littéralement.',
          'Les compagnies aériennes te remercient personnellement.',
          'Tu as collectionné plus de voyages que de souvenirs, semble-t-il.',
          'Le compte est resté à la maison à garder les valises.',
          'Ce mois-ci l’aventure a gagné contre le portefeuille.',
        ],
        low: [
          'Les valises sont restées tranquilles dans un coin ce mois-ci.',
          'Aucune nouvelle aventure, mais ton compte te remercie.',
          'Le passeport se repose un peu ce mois-ci.',
          'Tu as choisi le confort de la maison cette fois.',
          'Pas de vol, pas de valise : mois de repos.',
          'Les voyages attendent le bon moment, semble-t-il.',
          'Tu as mis l’explorateur en toi en pause.',
          'Zéro déplacement ce mois-ci, tellement de stabilité.',
        ],
      },
      altro: {
        high: [
          'Cette catégorie a eu son moment de gloire ce mois-ci.',
          'Quelque chose d’inattendu a frappé à ton portefeuille.',
          'Les dépenses diverses se sont fait remarquer, hein ?',
          'Un mois plein de petites surprises de dépenses.',
          'Les petites lignes ont pesé comme les grandes cette fois.',
          'Même l’imprévu a voulu sa part ce mois-ci.',
          'Quelques dépenses hors programme ont trouvé leur place dans le budget.',
          'Les exceptions ont été plus nombreuses que prévu ce mois-ci.',
        ],
        low: [
          'Aucune surprise de dépense ce mois-ci, quelle tranquillité.',
          'Les petites lignes sont restées vraiment petites cette fois.',
          'Un mois sans trop d’imprévus sur le portefeuille.',
          'Les dépenses diverses sont restées très basses.',
          'Peu d’exceptions, beaucoup de prévisibilité : pas mal.',
          'Le budget n’a eu aucune surprise hors programme.',
          'Ce mois-ci, l’imprévu a décidé de ne pas se montrer.',
          'Les dépenses hors catégorie sont restées silencieuses.',
        ],
      },
    },
    types: {
      budget_exceeded: [
        'Le budget a hissé le drapeau blanc ce mois-ci.',
        'On a explosé le plafond du budget, mais pas de panique.',
        'Le portefeuille a demandé une pause, ça arrive.',
        'Le budget s’est offert une petite liberté ce mois-ci.',
        'On a dépassé, mais ensemble on va remettre ça en ordre.',
        'Le budget a dit stop un peu plus tôt que prévu.',
        'On a dépassé, mais c’est un mois, pas une condamnation.',
        'Le compte a franchi la limite, on respire et on repart.',
      ],
      budget_respected: [
        'Eh bien... quelqu’un est en train d’apprendre ! 😂',
        'Budget respecté : tape m’en cinq.',
        'Tu as tenu le cap tout le mois.',
        'Le portefeuille te remercie personnellement ce mois-ci.',
        'Mission budget : accomplie.',
        'Tu as joué la défense et gagné le match.',
        'Le compte est serein, et moi aussi.',
        'Beau coup : budget respecté sans drame.',
      ],
      savings_vs_usual: [
        'Ton compte peut dormir tranquille aujourd’hui.',
        'Tu as dépensé moins que d’habitude, et ça se sent.',
        'Le portefeuille s’est offert des vacances loin du stress.',
        'Économies inattendues : qui es-tu et qu’as-tu fait du vrai toi ?',
        'Le compte a retrouvé un peu de souffle ce mois-ci.',
        'Tu as mis les économies en mode turbo, apparemment.',
        'Ton mois habituel a eu un joli rebondissement.',
        'Moins de sorties que prévu : belle surprise.',
      ],
      positive_streak: [
        'Tu es sous le budget depuis un moment, ça devient une habitude.',
        'Cette régularité commence vraiment à me plaire.',
        'Une autre bonne série : tu deviens doué pour ça.',
        'Ton budget a trouvé un sacré bon rythme.',
        'Mois après mois, cette discipline se voit.',
        'Continue comme ça et je vais devoir revoir ta réputation.',
      ],
      negative_streak: [
        'Le budget est sous pression depuis un moment, regardons ça ensemble.',
        'Quelques mois difficiles de suite, mais on peut toujours corriger le cap.',
        'Le compte demande un coup de main, sans drame.',
        'C’est le moment de remettre un peu d’ordre.',
        'Un peu plus d’attention ne ferait pas de mal, allez.',
        'Remettons les choses en ordre ensemble, tranquillement.',
      ],
      unusual_purchase: [
        'Une nouvelle entrée dans tes dépenses ce mois-ci !',
        'Voilà une catégorie qu’on n’avait pas vue depuis un moment.',
        'Une dépense jamais vue avant : bienvenue à la fête.',
        'Ton portefeuille a découvert un nouveau territoire.',
        'Une nouvelle entrée plutôt notable parmi tes dépenses.',
        'Une nouveauté vient rejoindre tes habitudes de dépense.',
      ],
      unusual_frequency_high: [
        'Combien de fois y es-tu retourné ce mois-ci ? J’ai perdu le compte.',
        'Tu y es retourné tellement de fois que ça ressemble à un abonnement.',
        'Cette catégorie t’a vu plus souvent que d’habitude.',
        'On dirait que c’est devenu ta destination préférée du mois.',
        'Tu y es pratiquement chez toi, à ce stade.',
        'Fréquence record ce mois-ci, bravo pour la régularité.',
      ],
      unusual_frequency_low: [
        'Tu es passé en mode discret sur cette catégorie.',
        'Peu de visites ce mois-ci, presque en pause.',
        'Cette catégorie s’est offert des vacances loin de toi.',
        'Tu n’y es passé qu’en coup de vent ce mois-ci.',
        'Presque absent sur cette catégorie. Respect.',
        'Tu as gardé tes distances, et ça se voit.',
      ],
      obiettivi: [
        'Ton objectif se rapproche, un pas à la fois.',
        'Chaque petite économie te rapproche de la ligne d’arrivée.',
        'La tirelire des objectifs grandit bien.',
        'Continue comme ça, l’objectif est plus proche que tu ne crois.',
        'Ton objectif te fait de l’œil.',
        'Tu es a {percentage} de "{goal}". Il reste {remaining} : ne lache pas maintenant.',
        '"{goal}" est a {percentage}. Le plus dur est deja derriere toi.',
        'Encore {remaining} et "{goal}" cesse d’etre une simple idee.',
        '{amount} mis de cote pour "{goal}". Ce n’est pas de la chance, c’est toi.',
      ],
      small_expenses_add_up: [
        'Elles ont l’air inoffensives, puis elles s’organisent entre elles.',
        'Une fois, ce n’est rien. {count} fois, ça commence a faire equipe.',
        '{count} petites depenses, {amount} au total. Les maths ne font pas de remise.',
        'Aucune n’est coupable. Toutes ensemble, un peu si.',
        'Des miettes, mais {count} miettes, ça finit par faire une part.',
        'Depenser peu {count} fois, ce n’est pas depenser peu.',
        'Ton portefeuille n’a rien vu venir. Moi si.',
        '{amount} partis a petites gorgees, sans meme un toast.',
      ],
      budget_high: [
        'Le budget est a bout de souffle : on est quasiment a l’arrivee, mais pas le mois.',
        'On est dans la partie du mois ou le budget retient sa respiration.',
        'Le budget tient encore debout, mais il s’appuie au mur.',
        'Il reste plus de mois que de budget, et on le sait tous les deux.',
        'Le budget vient d’entrer dans son acte final.',
        'A partir d’ici, chaque achat est un rebondissement.',
      ],
      budget_rising: [
        'Le budget a change de vitesse, et pas dans le bon sens.',
        'On a passe les trois quarts et la route est encore longue.',
        'Le budget commence doucement a transpirer.',
        'Tout va bien. Un peu moins bien qu’hier.',
        'On arrive au moment du mois ou je commence a regarder.',
        'Rien de dramatique. Juste moi, qui prends des notes.',
      ],
      fallback: [
        'J’ai remarqué quelque chose d’intéressant dans tes dépenses ce mois-ci.',
        'Il y a un petit mouvement à signaler, rien de grave.',
        'J’ai gardé un œil sur cette situation, et ça m’a fait sourire.',
        'Petite bizarrerie détectée, mais rien d’inquiétant.',
        'J’ai remarqué quelque chose d’inhabituel, juste pour t’informer avec style.',
        'Une petite curiosité venue de ton portefeuille ce mois-ci.',
      ],
    },
  },

  es: {
    categories: {
      ristoranti: {
        high: [
          '¿Le pagaste la cena también al chef? 😂',
          'Tu restaurante de confianza casi te pone una estatua en la entrada.',
          'A este ritmo mejor abres una cuenta con el camarero.',
          'Comiste como para dos... o para cuatro.',
          'El menú degustación esta vez lo hiciste tú solito.',
          'Cuidado, pronto te piden propina hasta del alquiler.',
          'Estás patrocinando personalmente la restauración local.',
          'La mesa con tu nombre ya es prácticamente oficial.',
          'Chef’s kiss para tu billetera, que aun así sobrevivió.',
          'Parece que llenaste el tanque de pizza más que de gasolina.',
          'Entre entrantes y postres, la cuenta hizo su propia carrera.',
          'El camarero ya te saluda por tu nombre. Mala señal (para la billetera).',
        ],
        low: [
          'Este mes gastaste tan poco en restaurantes que casi no te reconozco. 😂',
          'Tu restaurante de confianza se estará preguntando dónde te metiste.',
          'Parece que descubriste el secreto de la cocina de casa.',
          'El horno trabajó más horas extra que el delivery esta vez.',
          'El camarero sigue esperando, como en un pueblo fantasma.',
          'Te pasaste a modo chef casero sin avisar.',
          'Tu delantal está viviendo su momento de gloria.',
          'Dejaste los restaurantes en pausa este mes. Respeto.',
          'Hasta la pizza a domicilio se siente un poco olvidada.',
          'Felicidades, venciste la tentación del delivery.',
          'Tu nevera hizo más horas extra que de costumbre, ¿eh?',
          'Casi te graduaste en economía doméstica este mes.',
        ],
      },
      spesa: {
        high: [
          'La despensa está lista para un pequeño asedio. 😂',
          'Hiciste acopio como si llegara el invierno nuclear.',
          'El carrito necesitó refuerzos esta vez.',
          'El súper casi te dedicó un pasillo entero.',
          'A este ritmo podrías abrir un mini mercado en el salón.',
          'Compraste suficiente para alimentar también a los vecinos.',
          'La cajera ya te conoce de vista, imagino.',
          'Tu nevera necesita una ampliación.',
          'Parece que hiciste la compra para tres meses, no uno.',
          'La billetera sintió cada estantería esta vez.',
          'Llenaste el carrito como si fuera un refugio antiatómico.',
          'Bienvenida de nuevo, abundancia.',
        ],
        low: [
          'Este mes llevaste la billetera con correa corta. 😏',
          'La despensa se organizó sola, al parecer.',
          'Hiciste la compra en modo minimalista, y se nota.',
          'El carrito estuvo casi tímido esta vez.',
          'Bien hecho resistiendo las estanterías.',
          'La nevera está ligera, pero la conciencia tranquila.',
          'Entraste y saliste del súper casi en silencio.',
          'Hiciste la compra con el freno de mano puesto, y funcionó.',
          'Poca compra, mucha disciplina.',
          'Tu carrito hizo dieta contigo, al parecer.',
          'Dejaste casi todo en las estanterías, felicidades.',
          'La lista de la compra fue realmente corta este mes.',
        ],
      },
      shopping: {
        high: [
          '¿El armario todavía tenía espacio?! 😂',
          'Tu armario necesita más espacio este mes.',
          'Compraste como si las rebajas terminaran mañana.',
          'Las etiquetas de precio se asustaron un poco.',
          'El mensajero ya tiene tu timbre guardado en favoritos.',
          'Actualizaste el armario, la cuenta bancaria un poco menos.',
          'A este ritmo necesitas un segundo armario, no un descuento.',
          'Tu estilo subió de nivel, tu saldo un poco menos.',
          'Compraste como si fuera un deporte de competición.',
          'Esas no son bolsas del súper... son bolsas de compras.',
          'Tu billetera hizo su propio desfile de moda.',
          'Bienvenido a tu nuevo armario, básicamente.',
        ],
        low: [
          'Tu armario hoy por fin puede respirar.',
          'Resististe las rebajas como un verdadero héroe.',
          'Cero compras impulsivas este mes, qué disciplina.',
          'El mensajero casi se olvidó de ti, en el buen sentido.',
          'Dejaste los escaparates solo para mirar esta vez.',
          'El armario no recibió nuevos inquilinos este mes.',
          'Hiciste shopping solo con los ojos, y está perfecto así.',
          'Tu armario sigue igual, y la cuenta te lo agradece.',
          'Ninguna compra nueva, mucha autodisciplina.',
          'Le dijiste no a las rebajas, y se lo tomaron un poco personal.',
          'Tu estilo se quedó en lo clásico esta vez, y también funciona.',
          'Felicidades, ganaste tú contra los escaparates.',
        ],
      },
      trasporti: {
        high: [
          'El coche bebe más que tú. 😂',
          'La gasolinera ya reconoce el sonido de tu motor.',
          '¿Hiciste el recorrido de todo el país, o solo de la manzana?',
          'Tu coche merece un nombre propio a este punto.',
          'Llenar el tanque le costó horas de sueño a tu billetera esta vez.',
          'Parece que patrocinas personalmente la gasolina.',
          'Tu coche tuvo un apetito nada mal este mes.',
          'El medidor de consumo trabajó más que tú.',
          '¿Más kilómetros de lo previsto, o solo más paradas en la gasolinera?',
          'El tanque vivió una vida intensa este mes.',
          'Entre peajes y gasolina, el viaje costó más que el destino.',
          'Tu coche se siente mimado, la cuenta un poco menos.',
        ],
        low: [
          'Con lo que ahorraste, el coche casi se pagó solo. 😂',
          'Parece que descubriste las alegrías de la bicicleta.',
          'La gasolinera se estará preguntando dónde te metiste.',
          'Tu coche descansó más de lo habitual.',
          'Ahorraste gasolina como un verdadero maestro zen.',
          'El medidor de consumo se tomó un descanso este mes.',
          'Te convertiste en un maestro del ahorro sobre ruedas.',
          'Menos carretera, menos gasto: bonita ecuación.',
          'El tanque se mantuvo casi lleno todo el mes, felicidades.',
          'Dejaste el coche en el garaje más a menudo, y se nota.',
          'El transporte público te adoptó este mes, parece.',
          'Tu billetera se llenó de alivio, no de gasolina.',
        ],
      },
      casa: {
        high: [
          'Estas facturas, de verdad.',
          'La factura llegó sin avisar este mes.',
          'Algo en casa trabajó horas extra, ¿eh?',
          'Las facturas decidieron hacer horas extraordinarias.',
          'La lavadora merece una medalla, la cuenta no.',
          'Tu casa consume como una pequeña central, al parecer.',
          'El contador gira encantado, para él es un placer.',
          'Las facturas te enviaron un saludo bastante caro.',
          'Parece que calentaste también todo el barrio.',
          'La factura de la luz se tomó la revancha este mes.',
          'Tu casa está viviendo su etapa más energética.',
          'Los suministros decidieron hacerse notar esta vez.',
        ],
        low: [
          'La factura se presentó con buenos modales esta vez.',
          'Las facturas estuvieron casi tímidas este mes.',
          'Tu casa ahorró sin decírtelo siquiera.',
          'El contador se tomó una pausa, parece.',
          'Los suministros se comportaron muy bien este mes.',
          'Bonito ahorro silencioso en luz y gas.',
          'La factura decidió ser amable, por una vez.',
          'Tu casa entró en modo ahorro de energía.',
          'Los gastos del hogar bajaron sin hacer ruido.',
          'El contador te agradece la pausa.',
          'Facturas ligeras, conciencia tranquila.',
          'Tu casa ahorró más energía de lo que pensabas.',
        ],
      },
      abbonamenti: {
        high: [
          '¿Cuántos servicios de streaming estás viendo de verdad?',
          'Tu lista de suscripciones crece más rápido que tu serie favorita.',
          'Coleccionaste suscripciones como si fueran sellos.',
          'Cada mes nace una nueva suscripción, parece.',
          'Tu calendario de renovaciones está más lleno que tu tiempo libre.',
          'Estás pagando por entretenimiento que quizás ni abres.',
          'Las suscripciones se pusieron en fila y aumentaron.',
          'A este ritmo mereces una suscripción para tus suscripciones.',
        ],
        low: [
          'Hiciste limpieza entre las suscripciones, y se nota.',
          'Algunos servicios menos este mes, buena poda.',
          'Las suscripciones perdieron un suscriptor: tú.',
          'Le dijiste basta a un par de renovaciones automáticas, bien hecho.',
          'La lista de servicios activos se aligeró.',
          'Menos suscripciones, más espacio en el presupuesto.',
          'Pusiste orden entre las suscripciones, felicidades.',
          'Algunas renovaciones canceladas, la cuenta te lo agradece.',
        ],
      },
      tecnologia: {
        high: [
          'Un nuevo gadget acaba de entrar en la familia.',
          'La tienda de electrónica te esperaba con los brazos abiertos.',
          'Hiciste una actualización... tu cuenta también, pero en negativo.',
          'La tecnología te conquistó de nuevo este mes.',
          'Otro dispositivo se unió a la colección.',
          'Tu rincón tech se acaba de enriquecer.',
          'Caíste ante el encanto del último modelo, ¿eh?',
          'La caja de la tienda de electrónica imprimió un ticket nada despreciable.',
        ],
        low: [
          'Ningún gadget nuevo este mes: autocontrol de manual.',
          'Resististe el encanto de las novedades tech, felicidades.',
          'La tienda de electrónica ni te vio pasar.',
          'Cero compras tecnológicas, mucha fuerza de voluntad.',
          'Dejaste las novedades en el estante esta vez.',
          'Tu rincón tech sigue igual, y está perfecto así.',
          'Le dijiste no al último modelo, qué disciplina.',
          'Ningún dispositivo nuevo: tu billetera aplaude.',
        ],
      },
      salute: {
        high: [
          'Este mes de verdad te estás cuidando.',
          'La farmacia te vio más de lo habitual.',
          'Invertir en ti mismo no tiene precio... aunque la cuenta lo notó un poco.',
          'Tu bienestar tuvo prioridad este mes, y con razón.',
          'Gastaste más de lo habitual en tu salud, y está perfecto.',
          'La farmacia del barrio ya te considera casi de la familia.',
          'Cuidarse cuesta, pero siempre vale la pena.',
          'Este mes pusiste tu bienestar en primer lugar.',
        ],
        low: [
          'Pocos gastos de salud este mes, todo tranquilo.',
          'La farmacia te vio poco este mes, mejor así.',
          'Ningún achaque, ningún gasto: qué mes de suerte.',
          'Te mantuviste lejos de la farmacia, en el buen sentido.',
          'Salud en orden, cuenta en orden.',
          'Un mes tranquilo también para tu bienestar físico.',
          'Pocos gastos de salud, espero que solo porque estás bien.',
          'Tu cuerpo te dejó en paz este mes, al menos en la cuenta.',
        ],
      },
      svago: {
        high: [
          'Alguien está disfrutando la vida este mes.',
          'Tu ocio tuvo un mes espectacular.',
          'Invertiste bastante en divertirte, y se nota.',
          'El tiempo libre te costó este mes, pero qué vida.',
          'Llenaste el tanque de diversión más que de otra cosa.',
          'La diversión no se contuvo este mes.',
          'Gastaste para disfrutar la vida, y honestamente lo apruebo.',
          'Tu lado más juguetón ganó esta ronda.',
        ],
        low: [
          '¿Poco ocio este mes: todo trabajo y nada de diversión?',
          'La diversión se tomó una pausa este mes.',
          'Dejaste el tiempo libre un poco en segundo plano.',
          'Tu lado más juguetón se hizo pequeñito.',
          'Pocos gastos de ocio, espero que no por falta de ganas.',
          'La diversión espera su turno, al parecer.',
          'El relax pasó bastante desapercibido este mes.',
          'Poco ocio, mucha seriedad. ¿Quizás demasiada?',
        ],
      },
      viaggi: {
        high: [
          'Las maletas trabajaron más que tú este mes.',
          'Parece que perseguiste el verano por todo el mundo.',
          'El pasaporte todavía humea de tantos sellos.',
          'Invertiste bastante en nuevos horizontes, literalmente.',
          'Las aerolíneas te lo agradecen personalmente.',
          'Coleccionaste más viajes que recuerdos, al parecer.',
          'La cuenta se quedó en casa cuidando las maletas.',
          'Este mes la aventura le ganó a la billetera.',
        ],
        low: [
          'Las maletas se quedaron tranquilas en un rincón este mes.',
          'Ninguna aventura nueva, pero la cuenta te lo agradece.',
          'El pasaporte descansa un poco este mes.',
          'Elegiste la comodidad de casa esta vez.',
          'Nada de vuelos, nada de maletas: mes de descanso.',
          'Los viajes esperan el momento justo, al parecer.',
          'Pusiste en pausa al explorador que llevas dentro.',
          'Cero viajes este mes, mucha estabilidad.',
        ],
      },
      altro: {
        high: [
          'Esta categoría tuvo su momento de gloria este mes.',
          'Algo inesperado llamó a la puerta de tu billetera.',
          'Los gastos varios se hicieron notar, ¿eh?',
          'Un mes lleno de pequeñas sorpresas de gasto.',
          'Las partidas menores pesaron como las grandes esta vez.',
          'Hasta lo imprevisto quiso su parte este mes.',
          'Algunos gastos fuera de plan encontraron espacio en el presupuesto.',
          'Las excepciones fueron más numerosas de lo esperado este mes.',
        ],
        low: [
          'Ninguna sorpresa de gasto este mes, qué tranquilidad.',
          'Las partidas menores se quedaron realmente menores esta vez.',
          'Un mes sin demasiados imprevistos en la billetera.',
          'Los gastos varios se mantuvieron muy bajos.',
          'Pocas excepciones, mucha previsibilidad: no está mal.',
          'El presupuesto no tuvo sorpresas fuera de plan.',
          'Este mes lo imprevisto decidió no aparecer.',
          'Los gastos fuera de categoría se mantuvieron en silencio.',
        ],
      },
    },
    types: {
      budget_exceeded: [
        'El presupuesto izó la bandera blanca este mes.',
        'Rompimos el techo del presupuesto, pero sin pánico.',
        'La billetera pidió una pausa, pasa a veces.',
        'El presupuesto se tomó una libertad este mes.',
        'Nos pasamos, pero juntos lo ponemos en orden.',
        'El presupuesto dijo basta un poco antes de lo previsto.',
        'Nos excedimos, pero es un mes, no una condena.',
        'La cuenta superó el límite, respiramos y seguimos.',
      ],
      budget_respected: [
        'Mira tú... ¡alguien está aprendiendo! 😂',
        'Presupuesto respetado: choca esos cinco.',
        'Mantuviste el timón firme todo el mes.',
        'La billetera te lo agradece personalmente este mes.',
        'Misión presupuesto: cumplida.',
        'Jugaste a la defensa y ganaste el partido.',
        'La cuenta está tranquila, y yo también.',
        'Buena jugada: presupuesto respetado sin drama.',
      ],
      savings_vs_usual: [
        'Tu cuenta hoy puede dormir tranquila.',
        'Gastaste menos de lo habitual, y se siente.',
        'La billetera se tomó unas vacaciones del estrés.',
        'Ahorro inesperado: ¿quién eres y qué hiciste con el verdadero tú?',
        'La cuenta recuperó un poco de aire este mes.',
        'Le metiste turbo al ahorro, al parecer.',
        'Tu mes habitual tuvo un giro inesperado positivo.',
        'Menos gastos de lo previsto: bonita sorpresa.',
      ],
      positive_streak: [
        'Llevas un tiempo bajo presupuesto, y ya se está volviendo costumbre.',
        'Esta constancia me está empezando a gustar mucho.',
        'Otra racha positiva: te estás volviendo bueno en esto.',
        'Tu presupuesto encontró un ritmo nada mal.',
        'Mes tras mes, esta disciplina se nota.',
        'Sigue así y voy a tener que actualizar tu reputación.',
      ],
      negative_streak: [
        'El presupuesto está bajo presión desde hace un tiempo, miremos esto juntos.',
        'Unos meses difíciles seguidos, pero siempre se puede corregir el rumbo.',
        'La cuenta pide una mano, sin drama.',
        'Es momento de ordenar un poco las cosas.',
        'Un poco más de atención no vendría mal, vamos.',
        'Pongamos las cosas en orden juntos, con calma.',
      ],
      unusual_purchase: [
        '¡Una nueva entrada en tus gastos este mes!',
        'Aquí hay una categoría que no se veía desde hace tiempo.',
        'Un gasto nunca visto antes: bienvenido a la fiesta.',
        'Tu billetera descubrió un territorio nuevo.',
        'Una nueva entrada bastante notable entre tus gastos.',
        'Una novedad se une a tus hábitos de gasto.',
      ],
      unusual_frequency_high: [
        '¿Cuántas veces volviste allí este mes? Perdí la cuenta.',
        'Volviste tantas veces que ya parece una membresía.',
        'Esta categoría te vio más seguido de lo habitual.',
        'Parece que se volvió tu destino favorito del mes.',
        'A este ritmo ya eres prácticamente de la casa.',
        'Frecuencia récord este mes, felicidades por la constancia.',
      ],
      unusual_frequency_low: [
        'Estuviste en modo sigiloso con esta categoría.',
        'Pocas visitas este mes, casi en pausa.',
        'Esta categoría se tomó unas vacaciones de ti.',
        'Solo pasaste de refilón por aquí este mes.',
        'Casi ausente en esta categoría. Respeto.',
        'Mantuviste las distancias, y se nota.',
      ],
      obiettivi: [
        'Tu objetivo se acerca, un paso a la vez.',
        'Cada pequeño ahorro te acerca más a la meta.',
        'La alcancía de objetivos está creciendo bien.',
        'Sigue así, el objetivo está más cerca de lo que crees.',
        'Tu objetivo te está guiñando el ojo.',
        'Vas por el {percentage} de "{goal}". Faltan {remaining}: no aflojes ahora.',
        '"{goal}" va por el {percentage}. Lo dificil ya lo hiciste.',
        'Otros {remaining} y "{goal}" deja de ser solo una idea.',
        '{amount} apartados para "{goal}". Eso no es suerte, eres tu.',
      ],
      small_expenses_add_up: [
        'Parecen inofensivos, y luego se ponen de acuerdo entre ellos.',
        'Una vez no pesa. {count} veces ya empiezan a hacer equipo.',
        '{count} gastos pequenos, {amount} en total. Las matematicas no hacen descuentos.',
        'Ninguno es culpable. Todos juntos, un poco si.',
        'Migas, pero {count} migas, acaban siendo un trozo.',
        'Gastar poco {count} veces no es gastar poco.',
        'Tu cartera no se dio cuenta. Yo si.',
        '{amount} que se fueron a sorbitos, y sin un brindis.',
      ],
      budget_high: [
        'El presupuesto va sin aliento: estamos casi en la meta y el mes no.',
        'Estamos en la parte del mes en la que el presupuesto aguanta la respiracion.',
        'El presupuesto sigue en pie, pero apoyado en la pared.',
        'Queda mas mes que presupuesto, y los dos lo sabemos.',
        'El presupuesto ha entrado en su acto final.',
        'De aqui en adelante, cada compra es un giro de guion.',
      ],
      budget_rising: [
        'El presupuesto ha metido otra marcha, y no de las buenas.',
        'Hemos pasado tres cuartos y el camino todavia es largo.',
        'El presupuesto empieza a sudar un poco.',
        'Todo bien. Un poco menos bien que ayer.',
        'Llegamos al punto del mes en el que empiezo a mirar.',
        'Nada dramatico. Solo yo, tomando notas.',
      ],
      fallback: [
        'Noté algo interesante en tus gastos este mes.',
        'Hay un pequeño movimiento para señalar, nada grave.',
        'Estuve atento a esta situación, y me hizo sonreír.',
        'Pequeña rareza detectada, pero nada preocupante.',
        'Noté algo fuera de lo común, solo para avisarte con estilo.',
        'Una pequeña curiosidad de tu billetera este mes.',
      ],
    },
  },
}
